import { Activity, Server, Box, Shield, Network, FileText, Terminal, ArrowUpCircle, ChartNoAxesCombined, Database, Bot, Gamepad2, BrainCircuit, Radio, Link, PanelsTopLeft, Settings2, HardDrive, Workflow } from 'lucide-react';
export const navigation = [
  {to:'/',label:'Monitor',group:'OBSERVE',icon:Activity,description:'Fleet telemetry, findings, services and schedules'},
  {to:'/cockpit',label:'Host controls',group:'OBSERVE',icon:Server,description:'Reboot, service restarts, package upgrades and Wake-on-LAN'},
  {to:'/containers',label:'Containers',group:'OBSERVE',icon:Box,description:'Images, ports, compose projects and lifecycle controls'},
  {to:'/pihole',label:'DNS & network',group:'OBSERVE',icon:Network,description:'Pi-hole traffic, blocking and network health'},
  {to:'/trends',label:'History & trends',group:'OBSERVE',icon:ChartNoAxesCombined,description:'Historical resource and collector metrics'},
  {to:'/operations',label:'Findings inbox',group:'OPERATE',icon:Shield,description:'Filter, investigate and acknowledge findings'},
  {to:'/updates',label:'Updates',group:'OPERATE',icon:ArrowUpCircle,description:'Container image drift and security packages'},
  {to:'/reports',label:'Collectors & backups',group:'OPERATE',icon:FileText,description:'Report history, schedules, run controls and logs'},
  {to:'/security',label:'Security reports',group:'OPERATE',icon:Shield,description:'Host security audits and detailed evidence'},
  {to:'/logs',label:'Logs',group:'OPERATE',icon:Terminal,description:'Collector logs and container log viewer'},
  {to:'/streams',label:'Streams',group:'PERSONAL',icon:Radio,description:'Four-slot player, CS2 matches and channel directory'},
  {to:'/links',label:'Launchpad',group:'PERSONAL',icon:Link,description:'Homelab services and personal bookmarks'},
  {to:'/personal',label:'Media & widgets',group:'PERSONAL',icon:PanelsTopLeft,description:'Weather, downloads and price watch'},
  {to:'/bots',label:'Bots',group:'PERSONAL',icon:Bot,description:'Schedules, previews and bot configuration'},
  {to:'/leetify',label:'CS2 performance',group:'PERSONAL',icon:Gamepad2,description:'Match analysis, coaching and performance history'},
  {to:'/llm',label:'Local LLM',group:'PERSONAL',icon:BrainCircuit,description:'Models, grounded questions and runbooks'},
  {to:'/workspace',label:'Boards',group:'WORKSPACE',icon:PanelsTopLeft,description:'Create and customize widget dashboards'},
  {to:'/data',label:'Data pipeline',group:'WORKSPACE',icon:Workflow,description:'Collection, ingestion and database health'},
  {to:'/query',label:'Query console',group:'WORKSPACE',icon:Database,description:'Explore schema and saved read queries'},
  {to:'/samba',label:'Storage & shares',group:'WORKSPACE',icon:HardDrive,description:'Samba status, configuration and backups'},
  {to:'/tools',label:'Specialist tools',group:'WORKSPACE',icon:Workflow,description:'Architecture, Notes and agent workspace'},
  {to:'/settings',label:'Settings',group:'WORKSPACE',icon:Settings2,description:'Theme, density, motion and data permissions'},
];
