import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const require=createRequire(import.meta.url);
const {snapshot}=require('../backend/astra/fixtures.js');const channels=require('../backend/astra/channel-directory.json');
const css=['frontend/src/styles/tokens.css','frontend/src/astra/astra.css','frontend/src/astra/operational.css'].map(p=>fs.readFileSync(path.join(root,p),'utf8')).join('\n');
const spark=(color,offset=0)=>`<svg viewBox="0 0 260 40" role="img" aria-label="Illustrative history"><polyline fill="none" stroke="${color}" stroke-width="1.5" points="${Array.from({length:60},(_,i)=>`${i*4.4},${20+Math.sin(i*.8+offset)*13}`).join(' ')}"/></svg>`;
const hosts=snapshot.hosts.map(h=>`<article class="m-host p-searchable"><header><a href="#host"><h3>${h.id}</h3><small>${h.address}</small></a><span class="a-badge ${h.status}">${h.status}</span></header><p class="m-host-role">${h.role}</p><div class="m-telemetry"><div class="m-chart" style="color:var(--blue)"><span>CPU <b>${h.cpu??'—'}${h.cpu===null?'':'%'}</b></span>${h.cpu===null?'':spark('var(--blue)')}</div><div class="m-chart" style="color:var(--purple)"><span>RAM <b>${h.memory??'—'}${h.memory===null?'':'%'}</b></span>${h.memory===null?'':spark('var(--purple)',1)}</div><div class="m-host-readings"><span>TEMP <b>${h.temperature??'—'}°C</b></span><span>STORAGE <b>${h.storage}</b></span></div></div><footer><span>Sample observation</span><a href="#host">Inspect →</a></footer></article>`).join('');
const findings=snapshot.findings.map(f=>`<div class="m-finding p-searchable"><span class="a-badge ${f.severity}">${f.severity}</span><span><b>${f.message}</b><small>${f.host} / ${f.source} · sample</small></span><button class="a-button" onclick="this.textContent=this.textContent==='Reviewed'?'Review':'Reviewed'">Review</button></div>`).join('');
const nav=[['monitor','Monitor'],['host','Host details'],['findings','Findings'],['streams','Streams']].map(([id,label])=>`<a href="#${id}">${label}</a>`).join('');
const html=`<!doctype html><html lang="en" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pert’s Pocket · Design preview</title><style>${css}\n[hidden]{display:none!important}.p-view{min-width:0}.a-mobile-nav{gap:10px}.p-shortcuts{display:flex;gap:8px;flex-wrap:wrap}.p-shortcuts a{padding:12px 15px;background:var(--bg-inset);border:1px solid var(--border);border-radius:5px;color:var(--blue)}.a-topbar input{max-width:190px}.s-channel .a-button{margin-left:auto}@media(max-width:700px){.a-topbar input{max-width:145px}.m-host-readings b{font-size:10px}}</style></head><body class="astra-app"><a class="a-skip" href="#main-content">Skip to content</a><aside class="a-sidebar"><a class="a-brand" href="#monitor"><span class="m-brand-symbol">p<span>.</span></span><span>Pert’s Pocket<small>HOMELAB</small></span></a><nav class="m-nav-group"><p>DESIGN PREVIEW</p>${nav}</nav></aside><div class="a-main"><header class="a-topbar"><span class="a-breadcrumb">pocket / preview</span><input aria-label="Filter sample content" placeholder="Filter sample content…" oninput="filter(this.value)"><button class="a-button" onclick="document.documentElement.dataset.theme=document.documentElement.dataset.theme==='light'?'dark':'light'">Theme</button></header><main class="a-content" id="main-content"><div class="m-mode-strip">SAMPLE DATA · Standalone HTML · No network requests or real operations</div>
<section class="p-view" id="monitor"><div class="m-title"><div><span class="m-kicker">FLEET / OVERVIEW</span><h1>Monitor</h1></div><a class="a-button" href="#streams">Open Streams →</a></div><div class="m-stat-grid">${[['HOSTS','3 / 4','green'],['SERVICES','9 / 9','aqua'],['FINDINGS','1','orange'],['DNS QUERIES','148,920','blue'],['COLLECTORS','6','purple'],['NEXT JOB','20m','yellow']].map(([label,value,color])=>`<div class="m-stat" style="border-top-color:var(--${color})"><span>${label}</span><strong style="color:var(--${color})">${value}</strong><small>Illustrative status</small></div>`).join('')}</div><div class="m-section-head"><h2>Host telemetry</h2><span>Fictional measurements</span></div><div class="m-host-grid">${hosts}</div><div class="m-work-grid"><section class="m-panel"><header><h2>Findings & recent changes</h2><a href="#findings">Inbox →</a></header>${findings}</section><section class="m-panel"><header><h2>Quick access</h2><a href="#streams">Streams →</a></header><a class="m-stream-shortcut" href="#streams"><span><strong>Stream station</strong><small>Four slots · CS2 match guide · favorites</small></span>↗</a><div class="p-shortcuts"><a href="http://rpi.lan/admin">Pi-hole ↗</a><a href="http://jellyfin.lan:8096/">Jellyfin ↗</a><a href="http://opti.lan/">OpenMediaVault ↗</a><a href="http://noblenumbat.lan:9000/">Portainer ↗</a></div><div class="m-section-head"><h2>Scheduled work</h2></div><div class="m-change">homelab-doctor.timer <time>in 20m</time></div><div class="m-change">coldcopy.timer <time>in 3d</time></div></section></div></section>
<section class="p-view" id="host" hidden><h1>Host inspection</h1><p class="a-muted">The running app has per-host vitals, SMART, disk, network, container and control views.</p><div class="m-host-grid">${hosts}</div><div class="m-work-grid"><div class="m-panel"><header><h2>Storage / opti</h2></header><div class="a-row">Pool red <b>61% used</b></div><div class="a-row">Capacity <b>3.6 TB</b></div><div class="a-row">SMART <span class="a-badge healthy">PASSED · sample</span></div></div><div class="m-panel"><header><h2>Services / rpi</h2></header>${snapshot.services.filter(s=>s.host==='rpi').map(s=>`<div class="a-row">${s.name}<span class="a-badge healthy">healthy · sample</span></div>`).join('')}</div></div></section>
<section class="p-view" id="findings" hidden><h1>Findings inbox</h1><p class="a-muted">Local review controls below affect this HTML page only.</p><div class="m-panel">${findings}</div></section>
<section class="p-view" id="streams" hidden><h1>Streams</h1><div class="s-layout"><section><div class="s-player"><div class="s-player-empty"><h2 id="sample-channel">Stream station</h2><p>Choose a channel below to simulate selection.</p><span>OFFLINE SAMPLE · NO VIDEO</span></div></div><div class="s-slots" style="margin-top:12px">${[1,2,3,4].map(i=>`<button onclick="document.querySelectorAll('.s-slots button').forEach(b=>b.classList.remove('active'));this.classList.add('active')"><span>0${i}</span><strong>Slot ${i}</strong><small>sample</small></button>`).join('')}</div><p class="s-notice">The running app adds HLS playback, quality/buffer profiles, recent channels, persistent favorites, and HLTV match discovery.</p></section><section>${channels.groups.flatMap(g=>g.channels).slice(0,8).map(c=>`<div class="s-channel p-searchable"><span class="s-platform">TW</span><span><strong>${c.label}</strong><small>${c.channel} · live status unknown</small></span><button class="a-button" onclick="document.getElementById('sample-channel').textContent='${c.channel} · simulated'">Select</button></div>`).join('')}<p class="s-provenance">The app uses Valve Regional Standings supplied through HLTV for top-20 eligibility. Premier-series labels are distinct from verified S-tier metadata.</p></section></div></section>
<footer class="a-footer"><span>Pert’s Pocket</span><span>Open the full local app for every feature · port 5174</span></footer></main></div><nav class="a-mobile-nav">${nav}</nav><script>function route(){const id=location.hash.slice(1)||'monitor';document.querySelectorAll('.p-view').forEach(v=>v.hidden=v.id!==id);document.querySelectorAll('.a-sidebar nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+id));window.scrollTo(0,0)}function filter(value){document.querySelectorAll('.p-searchable').forEach(el=>el.hidden=!el.textContent.toLowerCase().includes(value.toLowerCase()))}addEventListener('hashchange',route);route();</script></body></html>`;
fs.writeFileSync(path.join(root,'design/astra-preview.html'),html);
console.log('Updated design/astra-preview.html — self-contained, no automatic requests');
