// Local preview contract smoke. Read-only except probes of permanently blocked routes.
import fs from 'node:fs';
const args=process.argv.slice(2);const arg=(key,fallback)=>{const i=args.indexOf('--'+key);return i<0?fallback:args[i+1]};
const base=arg('base','http://127.0.0.1:3003');
const origin=new URL(base);if(!['127.0.0.1','localhost','[::1]'].includes(origin.hostname))throw new Error('Preview smoke is restricted to loopback. Use the retained legacy smoke separately for deployment.');
const routes=['/api/health','/api/astra/capabilities','/api/astra/snapshot','/api/astra/preferences','/api/astra/actions','/api/astra/streams/guide','/api/streams/status','/api/streams/presets','/api/hltv/day','/api/hltv/vrs','/api/vitals','/api/vitals/rpi','/api/vitals/android','/api/containers','/api/timers','/api/activity','/api/agents','/api/updates','/api/reports','/api/reports/journal-hunt-latest','/api/runners','/api/runners/hardware-latest','/api/runners/homelab-doctor-latest/history','/api/runners/homelab-doctor-latest/log','/api/pihole/summary','/api/pihole/top','/api/pihole/blocking','/api/uptime','/api/linkcheck','/api/trends','/api/hldb/schema','/api/hldb/dataplane','/api/hldb/changes','/api/hldb/metrics','/api/hldb/status','/api/hldb/health','/api/hldb/search?q=backup','/api/samba/status','/api/samba/config','/api/samba/backups','/api/llama/status','/api/llama/models','/api/llama/runbooks','/api/weather/config','/api/weather/preview','/api/pricewatch','/api/ui/boards','/api/ui/settings'];
const results={};let failures=0;
const caps=await fetch(base+'/api/astra/capabilities').then(r=>r.json());if(caps.mode!=='demo')throw new Error('Smoke expects demo mode. Select Demo in Settings; smoke will not change your mode automatically.');
for(const route of routes){const r=await fetch(base+route,{signal:AbortSignal.timeout(10000)});let body;try{body=await r.json()}catch{body={}};const pass=r.status===200;results['GET '+route]={status:r.status,keys:Object.keys(body).sort()};if(!pass){failures++;console.error('FAIL',route,r.status,body.error)}}
for(const route of ['/api/architecture/ingest','/api/hldb/query','/api/llama/ask','/api/samba/config']){const r=await fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});results['POST '+route]={status:r.status};if(r.status!==403){failures++;console.error('FAIL forbidden route',route,r.status)}}
const compare=arg('compare',null);if(compare){const baseline=JSON.parse(fs.readFileSync(compare,'utf8'));for(const [key,old]of Object.entries(baseline)){const next=results[key];if(!next||old.status!==next.status||(old.keys||[]).some(k=>!next.keys.includes(k))){failures++;console.error('Contract drift:',key)}}}
const capture=arg('capture',null);if(capture)fs.writeFileSync(capture,JSON.stringify(results,null,2)+'\n');
console.log(`${Object.keys(results).length} preview API checks; ${failures} failures`);process.exitCode=failures?1:0;