import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Radio, ArrowUpRight, Server, AlertTriangle } from 'lucide-react';
import { useSnapshot, usePreferences, age, health, launchers } from './data';
import { useVitalsRange, type VitalsRange, useRunners, useUptime } from '../lib/queries';
import { Sparkline } from '../widgets/kit';
import { Badge, ErrorText } from './ui';
import { SnapshotNotice } from './Infrastructure';
import { Instrument } from './Instruments';
function HostTelemetry({id,range}:{id:string;range:VitalsRange}) {
 const q=useVitalsRange(id,range);const latest=q.data?.latest;const samples=q.data?.samples||[];
 return <div className="m-telemetry"><div className="m-chart" style={{color:'var(--blue)'}}><span>CPU <b>{latest?.cpu_pct==null?'—':`${latest.cpu_pct.toFixed(0)}%`}</b></span><Sparkline values={samples.map(s=>s.cpu_pct)} times={samples.map(s=>s.t)} width={260} height={40} label={`${id} CPU`} format={v=>`${v.toFixed(1)}%`}/></div><div className="m-chart" style={{color:'var(--purple)'}}><span>RAM <b>{latest?.mem_pct==null?'—':`${latest.mem_pct.toFixed(0)}%`}</b></span><Sparkline values={samples.map(s=>s.mem_pct)} times={samples.map(s=>s.t)} width={260} height={40} label={`${id} memory`} format={v=>`${v.toFixed(1)}%`}/></div><div className="m-host-readings"><span>TEMP <b>{latest?.temp_c==null?'—':`${latest.temp_c}°C`}</b></span><span>RX <b>{latest?.rx_bps==null?'—':`${(latest.rx_bps/1024).toFixed(0)} KiB/s`}</b></span><span>TX <b>{latest?.tx_bps==null?'—':`${(latest.tx_bps/1024).toFixed(0)} KiB/s`}</b></span></div><ErrorText error={q.error}/>{!samples.length&&<p className="a-stamp">No telemetry available. Values are unknown.</p>}</div>;
}
export default function Monitor(){
 const q=useSnapshot(),prefs=usePreferences(),runners=useRunners(),uptime=useUptime();const [range,setRange]=useState<VitalsRange>('1h');const d=q.data;
 if(!d)return <><h1>Monitor</h1><ErrorText error={q.error}/><p>Loading telemetry…</p></>;
 const healthy=d.hosts.filter(h=>(d.mode==='demo'?h.status:health(h))==='healthy').length;const open=d.findings.filter(f=>!['info','ok'].includes(f.severity)&&!prefs.data?.acknowledgements.includes(f.id));
 const favorites=launchers(prefs.data).filter(l=>prefs.data?.favorites.includes(l.id));
 return <><div className="m-title"><div><span className="m-kicker">FLEET / OVERVIEW</span><h1>Monitor</h1></div><div className="m-title-actions"><label>History <select aria-label="Telemetry range" value={range} onChange={e=>setRange(e.target.value as VitalsRange)}>{['1h','3h','9h','24h','48h'].map(r=><option key={r}>{r}</option>)}</select></label><Link className="a-button" to="/cockpit">Host controls <ArrowUpRight size={14}/></Link></div></div>
 <SnapshotNotice/>
 <div className="m-stat-grid">{[{label:'HOSTS REPORTING',value:`${healthy} / ${d.hosts.length}`,note:d.hosts.filter(h=>(d.mode==='demo'?h.status:health(h))!=='healthy').map(h=>h.id).join(', ')||'All current',tone:'green',to:'/cockpit'},{label:'SERVICE MONITORS',value:uptime.data?`${uptime.data.up} / ${uptime.data.total}`:'—',note:uptime.error?'Monitor source unavailable':'Last reported availability',tone:'aqua',to:'/containers'},{label:'OPEN FINDINGS',value:open.length,note:'Unacknowledged warnings',tone:'orange',to:'/operations'},{label:'DNS QUERIES',value:d.dns?.dns_queries_today?.toLocaleString()||'—',note:`${d.dns?.ads_percentage_today??'—'}% blocked today`,tone:'blue',to:'/pihole'},{label:'COLLECTORS',value:runners.data?.runners.length??'—',note:`${runners.data?.runners.filter(r=>r.stale).length??'—'} stale reports`,tone:'purple',to:'/reports'},{label:'NEXT MAINTENANCE',value:d.schedules[0]?.next?age(d.schedules[0].next):'Unknown',note:d.schedules[0]?.unit||'No schedule available',tone:'yellow',to:'/operations?tab=maintenance'}].map(s=><Link className="m-stat" key={s.label} to={s.to} style={{borderTopColor:`var(--${s.tone})`}}><span>{s.label}</span><strong style={{color:`var(--${s.tone})`}}>{s.value}</strong><small>{s.note}</small></Link>)}</div>
 <div className="m-section-head"><h2><Server size={16}/> Host telemetry</h2><span>{d.mode==='demo'?'Sample observations':'Latest observations'} · {age(d.observedAt)}</span></div>
 <div className="m-host-grid">{d.hosts.map(h=><section className="m-host" key={h.id}><header><Link to={`/infrastructure/hosts/${h.id}`}><h3>{h.id}</h3><small>{h.address}</small></Link><Badge status={d.mode==='demo'?h.status:health(h)}/></header><p className="m-host-role">{h.role}</p><HostTelemetry id={h.id} range={range}/><footer><span>{h.uptime==null?'Uptime unknown':`${Math.floor(h.uptime/86400)}d uptime`} · {age(h.observedAt)}</span><Link to={`/infrastructure/hosts/${h.id}`}>Inspect →</Link></footer></section>)}</div>
 <div className="m-work-grid"><section className="m-panel"><header><h2><AlertTriangle size={16}/> Requires attention <span className="m-count">{open.length}</span></h2><Link to="/operations">Inbox →</Link></header>{open.length?open.slice(0,4).map(f=><Link className="m-finding" key={f.id} to={`/operations?search=${encodeURIComponent(f.message)}`}><Badge status={f.severity}/><span><b>{f.message}</b><small>{f.host||'Fleet'} · {f.source} · {age(f.ts)}</small></span><ArrowUpRight size={14}/></Link>):<p className="m-empty">No unacknowledged findings in the available data.</p>}<div className="m-section-head"><h2>Recent changes</h2><Link to="/operations?tab=activity">Activity →</Link></div>{d.findings.slice(0,3).map(f=><div className="m-change" key={f.id}><span className="m-dot"/><span>{f.message}<small>{f.host} / {f.source}</small></span><time>{age(f.ts)}</time></div>)}</section>
 <section className="m-panel"><header><h2>Quick access</h2><Link to="/links">All services →</Link></header><Link className="m-stream-shortcut" to="/streams"><Radio size={28}/><span><strong>Stream station</strong><small>Player · CS2 match guide · channels</small></span><ArrowUpRight size={20}/></Link><div className="m-favorites">{favorites.map(l=><a key={l.id} href={l.url} target="_blank" rel="noreferrer"><img src={l.icon} alt=""/><span>{l.name}</span><ArrowUpRight size={12}/></a>)}</div>{!favorites.length&&<Link to="/links">Choose favorites in Launchpad</Link>}<div className="m-section-head"><h2>Scheduled jobs</h2><Link to="/reports">Collectors →</Link></div>{d.schedules.slice(0,4).map(s=><div className="m-change" key={s.host+s.unit}><span className="m-dot" style={{background:'var(--purple)'}}/><span>{s.unit}<small>{s.host}</small></span><time>{age(s.next)}</time></div>)}</section></div>
 <div className="m-widget-grid">{['storage','network','vpn','downloads','db-health','monitors'].map(type=><Instrument key={type} type={type}/>)}</div>
 </>;
}
