import { lazy, Suspense, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Search, Check, Bookmark, ArrowUpRight, Plus, Star, Trash2, Pencil, ShieldCheck, Radio } from 'lucide-react';
import { useSnapshot,usePreferences,useSavePreferences,LEGACY,tools,launchers,type Finding } from './data';
import { Heading,Panel,Badge,Stamp,Empty,ErrorText,Dialog,More } from './ui';
import { SnapshotNotice } from './Infrastructure';
import { get } from '../lib/api';

const FeatureWidgets=lazy(()=>import('./Widgets'));

export function Operations(){
 const [params,setParams]=useSearchParams();const q=useSnapshot();const prefs=usePreferences();const save=useSavePreferences();const [viewName,setViewName]=useState('');const [saveOpen,setSaveOpen]=useState(false);
 const tab=params.get('tab')||'inbox';const host=params.get('host')||'';const severity=params.get('severity')||'';const search=params.get('search')||'';const showAck=params.get('ack')==='1';const selected=q.data?.findings.find(f=>f.id===params.get('finding'));
 const update=(key:string,value:string)=>setParams(p=>{if(value)p.set(key,value);else p.delete(key);return p});
 const items=q.data?.findings.filter(f=>(!host||f.host===host)&&(!severity||f.severity===severity)&&(!search||(f.message+' '+f.source).toLowerCase().includes(search.toLowerCase()))&&(tab==='activity'||!['info','ok'].includes(f.severity))&&(tab==='activity'||showAck||!prefs.data?.acknowledgements.includes(f.id)))||[];
 const ack=(f:Finding)=>{if(!prefs.data)return;const has=prefs.data.acknowledgements.includes(f.id);save.mutate({...prefs.data,acknowledgements:has?prefs.data.acknowledgements.filter(id=>id!==f.id):[...prefs.data.acknowledgements,f.id].slice(-500)})};
 const reports=useQuery({queryKey:['astra-maintenance-reports'],queryFn:async()=>{const routes=['software-latest','coldcopy-latest','network-latest'];return Promise.all(routes.map(async name=>{try{return {name,data:await get<unknown>(`/api/runners/${name}`),error:null}}catch(e){return {name,data:null,error:(e as Error).message}}}))},enabled:tab==='maintenance',staleTime:300000});
 return <><Heading eyebrow="OPERATIONS" title="Findings & maintenance" description="Filter by host, severity and source; save views and acknowledge locally." actions={<button className="a-button" onClick={()=>setSaveOpen(true)}><Bookmark size={16}/> Save view</button>}/><SnapshotNotice/><div className="a-tabs" aria-label="Operations views">{[['inbox','Findings inbox'],['activity','Activity'],['maintenance','Maintenance']].map(([id,label])=><button key={id} aria-pressed={tab===id} className={tab===id?'active':''} onClick={()=>update('tab',id)}>{label}</button>)}</div><ErrorText error={save.error}/>
 {tab==='maintenance'?<div className="a-detail-grid"><Panel title="Scheduled work">{q.data?.schedules.map(s=><div className="a-schedule" key={s.host+s.unit}><span className="a-grow"><strong>{s.unit}</strong><small>{s.host} · last: {s.passed||'not recorded'}</small></span><Stamp value={s.next}/></div>)}{!q.data?.schedules.length&&<Empty>No timer observations available.</Empty>}</Panel><Panel title="Reports to review"><p className="a-muted">Updates, backups, and network checks retain their original collector timestamps.</p><ErrorText error={reports.error}/>{reports.data?.map(r=><details key={r.name}><summary>{r.name.replace('-latest','')}</summary><ErrorText error={r.error}/>{r.data!==null&&<pre className="a-json">{JSON.stringify(r.data,null,2)}</pre>}</details>)}</Panel></div>:<Panel title={tab==='activity'?'Recent activity':'Findings inbox'} aside={<span className="a-count">{items.length}</span>}><div className="a-toolbar"><label className="a-search-field"><Search size={17}/><input value={search} onChange={e=>update('search',e.target.value)} placeholder="Filter findings…" aria-label="Search findings"/></label><select value={host} onChange={e=>update('host',e.target.value)} aria-label="Filter findings by host"><option value="">All hosts</option>{q.data?.hosts.map(h=><option key={h.id}>{h.id}</option>)}</select><select value={severity} onChange={e=>update('severity',e.target.value)} aria-label="Filter by severity"><option value="">All severities</option>{Array.from(new Set(q.data?.findings.map(f=>f.severity))).map(s=><option key={s}>{s}</option>)}</select><label className="a-check"><input type="checkbox" checked={showAck} onChange={e=>update('ack',e.target.checked?'1':'')}/> Include reviewed</label></div>{items.map(f=><div className="a-finding-row" key={f.id}><button className="a-finding-main" onClick={()=>update('finding',f.id)}><Badge status={f.severity}/><span className="a-grow"><strong>{f.message}</strong><small>{f.host||'Fleet'} · {f.source} · <Stamp value={f.ts}/></small></span></button><button className={`a-icon ${prefs.data?.acknowledgements.includes(f.id)?'selected':''}`} disabled={save.isPending||!prefs.data} aria-label={`${prefs.data?.acknowledgements.includes(f.id)?'Unacknowledge':'Acknowledge'} ${f.message}`} onClick={()=>ack(f)}><Check size={18}/></button></div>)}{!items.length&&<Empty>No findings match this view.</Empty>}</Panel>}
 {selected&&<Dialog title="Finding details" onClose={()=>update('finding','')}><Badge status={selected.severity}/><h3 className="a-detail-title">{selected.message}</h3><p className="a-muted">{selected.detail||'This finding is reported by the source below. Review its evidence before taking action.'}</p><div className="a-row"><span>Source</span><strong>{selected.source}</strong></div><div className="a-row"><span>Observed</span><Stamp value={selected.ts}/></div><div className="a-toolbar">{selected.host&&<Link className="a-button" to={`/infrastructure/hosts/${selected.host}`}>Open host</Link>}<Link className="a-button" to="/workspace?tab=data">Explore reports</Link><a className="a-button" href={`${LEGACY}/dozzle/`} target="_blank" rel="noreferrer">Logs in existing tool <ArrowUpRight size={14}/></a></div><button className="a-button primary" disabled={save.isPending||!prefs.data} onClick={()=>ack(selected)}>{prefs.data?.acknowledgements.includes(selected.id)?'Mark unreviewed':'Acknowledge locally'}</button><ErrorText error={save.error}/></Dialog>}
 {saveOpen&&<Dialog title="Save this operations view" onClose={()=>setSaveOpen(false)}><form onSubmit={e=>{e.preventDefault();if(prefs.data&&viewName.trim())save.mutate({...prefs.data,savedViews:[...prefs.data.savedViews,{name:viewName.trim(),path:'/operations?'+params.toString()}]},{onSuccess:()=>setSaveOpen(false)})}}><label className="a-field">View name<input required maxLength={60} autoFocus value={viewName} onChange={e=>setViewName(e.target.value)}/></label><button className="a-button primary" disabled={save.isPending||!prefs.data}>Save view</button><ErrorText error={save.error}/></form></Dialog>}</>;
}
export function Personal({launchpad=false}:{launchpad?:boolean}){
 const [params,setParams]=useSearchParams();const tab=launchpad?'apps':(params.get('tab')||'media');const [search,setSearch]=useState('');const prefs=usePreferences();const save=useSavePreferences();const q=useSnapshot();const [editing,setEditing]=useState<{id:string;name:string;url:string;group:string}|null>(null);
 const apps=launchers(prefs.data).filter(l=>(l.name+' '+l.group).toLowerCase().includes(search.toLowerCase()));
 const toggle=(id:string)=>prefs.data&&save.mutate({...prefs.data,favorites:prefs.data.favorites.includes(id)?prefs.data.favorites.filter(x=>x!==id):[...prefs.data.favorites,id]});
 return <><Heading eyebrow="PERSONAL" title="Services & bookmarks" description="Pin services, organize links, and add your own destinations." actions={<button className="a-button" onClick={()=>setEditing({id:crypto.randomUUID(),name:'',url:'https://',group:'My apps'})}><Plus size={17}/> Add launcher</button>}/><div className="a-tabs" aria-label="Personal areas">{[['apps','Your apps'],['media','Media'],['weather','Weather'],['gaming','Gaming'],['price','Price watch'],['bots','Bots'],['llm','Local AI']].map(([id,label])=><button className={tab===id?'active':''} aria-pressed={tab===id} key={id} onClick={()=>setParams({tab:id})}>{label}</button>)}</div><ErrorText error={save.error||prefs.error}/>
 {tab==='apps'?<><div className="a-toolbar"><label className="a-search-field"><Search size={17}/><input aria-label="Search launchers" placeholder="Find an app or group…" value={search} onChange={e=>setSearch(e.target.value)}/></label><p className="a-stamp">Stars pin apps to your favorites.</p></div><div className="a-app-grid">{apps.sort((a,b)=>Number(prefs.data?.favorites.includes(b.id))-Number(prefs.data?.favorites.includes(a.id))).map(l=><div className="a-app-card" key={l.id}><a href={l.url} target="_blank" rel="noreferrer"><img src={l.icon} alt=""/><span><strong>{l.name}</strong><small>{l.group} · opens existing service</small></span><ArrowUpRight size={15}/></a><div className="a-app-card-actions"><button className={`a-icon ${prefs.data?.favorites.includes(l.id)?'selected':''}`} aria-label={`Favorite ${l.name}`} disabled={!prefs.data||save.isPending} onClick={()=>toggle(l.id)}><Star size={16}/></button>{l.custom&&<><button className="a-icon" aria-label={`Edit ${l.name}`} onClick={()=>setEditing(l)}><Pencil size={15}/></button><button className="a-icon" aria-label={`Remove ${l.name}`} disabled={save.isPending} onClick={()=>prefs.data&&save.mutate({...prefs.data,launchers:prefs.data.launchers.filter(x=>x.id!==l.id),favorites:prefs.data.favorites.filter(id=>id!==l.id)})}><Trash2 size={15}/></button></>}</div></div>)}</div>{!apps.length&&<Empty>No matching launchers.</Empty>}<Panel title="Specialist tools" aside={<Badge>Existing site</Badge>}><div className="a-tool-grid">{tools.map(t=><a key={t.path} className="a-tool" href={LEGACY+t.path} target="_blank" rel="noreferrer"><span><strong>{t.name}</strong><small>{t.description}</small></span><ArrowUpRight size={17}/></a>)}</div></Panel></>:tab==='llm'?<div className="a-detail-grid"><Panel title="Local intelligence" aside={<Radio size={19}/>}><h3>android · Galaxy S10</h3><p className="a-muted">The local model runs on an intermittent host. Its absence does not mean the rest of the homelab is down.</p><Badge status={q.data?.hosts.find(h=>h.id==='android')?.status||'unknown'}/><div className="a-toolbar"><More to="/infrastructure/hosts/android">Host details</More><a className="a-button" href={`${LEGACY}/llm`} target="_blank" rel="noreferrer">Open existing LLM tool <ArrowUpRight size={15}/></a></div></Panel><Panel title="Preview permissions" aside={<ShieldCheck size={18}/>}><p className="a-muted">This preview does not send prompts, start models, or change the phone in this preview. Use global search to read the available runbook index.</p></Panel></div>:<Suspense fallback={<Empty>Opening integrations…</Empty>}><FeatureWidgets area={tab}/></Suspense>}
 {editing&&<Dialog title={prefs.data?.launchers.some(l=>l.id===editing.id)?'Edit launcher':'Add launcher'} onClose={()=>setEditing(null)}><form onSubmit={e=>{e.preventDefault();if(!prefs.data)return;save.mutate({...prefs.data,launchers:[...prefs.data.launchers.filter(l=>l.id!==editing.id),{id:editing.id,name:editing.name,url:editing.url,group:editing.group}]},{onSuccess:()=>setEditing(null)})}}><label className="a-field">Name<input required maxLength={80} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label className="a-field">URL<input required type="url" pattern="https?://.*" value={editing.url} onChange={e=>setEditing({...editing,url:e.target.value})}/></label><label className="a-field">Group<input required maxLength={60} value={editing.group} onChange={e=>setEditing({...editing,group:e.target.value})}/></label><button className="a-button primary" disabled={save.isPending}>Save launcher</button><ErrorText error={save.error}/></form></Dialog>}</>;
}
