import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowUpRight, Server, FileText, HardDrive } from 'lucide-react';
import { get } from '../lib/api';
import { useRunners } from '../lib/queries';
import { LEGACY,tools,useSnapshot,age } from './data';
import { Panel,ErrorText,Badge } from './ui';
import { Instrument } from './Instruments';
export default function Tools({area}:{area:string}){
 const snapshot=useSnapshot(),runners=useRunners();const [runner,setRunner]=useState('homelab-doctor-latest'),[storageTab,setStorageTab]=useState('status');
 const log=useQuery({queryKey:['tool-log',runner],queryFn:()=>get<{lines?:string[];log?:string;tail?:string}>(`/api/runners/${runner}/log?lines=200`),enabled:area==='logs',refetchInterval:10000});
 const shares=useQuery({queryKey:['tool-samba',storageTab],queryFn:()=>get<Record<string,unknown>>('/api/samba/'+storageTab),enabled:area==='samba',refetchInterval:60000});
 return <>{area==='logs'?<><div className="a-toolbar"><label className="a-field">Collector<select value={runner} onChange={e=>setRunner(e.target.value)}>{(runners.data?.runners||[]).map(r=><option key={r.name} value={r.name}>{r.label}</option>)}</select></label><button className="a-button" disabled={log.isFetching} onClick={()=>log.refetch()}>Refresh log</button><a className="a-button" href={LEGACY+'/dozzle/'} target="_blank" rel="noreferrer">Container logs · Dozzle <ArrowUpRight size={15}/></a></div><Panel title="Collector output"><ErrorText error={log.error}/><pre className="m-log" tabIndex={0}>{log.data?.lines?.join('\n')||log.data?.log||log.data?.tail||'No log output available.'}</pre><small className="a-stamp">{log.dataUpdatedAt?`Retrieved ${age(new Date(log.dataUpdatedAt).toISOString())}`:'Waiting for log source'}</small></Panel></>:area==='samba'?<><div className="m-widget-grid"><Instrument type="storage"/><Instrument type="db-health"/></div><Panel title="Samba · opti" aside={<HardDrive size={18}/>}><div className="a-tabs">{['status','config','backups'].map(t=><button key={t} aria-pressed={storageTab===t} className={storageTab===t?'active':''} onClick={()=>setStorageTab(t)}>{t}</button>)}</div><ErrorText error={shares.error}/>{shares.data&&<pre className="a-json" tabIndex={0}>{typeof shares.data.config==='string'?shares.data.config:JSON.stringify(shares.data,null,2)}</pre>}<a className="a-button" href={LEGACY+'/samba/'} target="_blank" rel="noreferrer">Open share editor & rollback tools <ArrowUpRight size={15}/></a></Panel></>:null}
 {['architecture','agents','agentic','tools'].includes(area)&&<Panel title="Host & service map"><div className="m-topology"><div className="m-topology-root">LAN / WireGuard<small>Pi-hole DNS · rpi</small></div><div className="m-topology-hosts">{snapshot.data?.hosts.map(h=><div key={h.id}><Link to={`/infrastructure/hosts/${h.id}`}><Server size={18}/><strong>{h.id}</strong><Badge status={h.status}/></Link><small>{h.address} · {h.role}</small>{snapshot.data?.services.filter(s=>s.host===h.id).map(s=><span className="m-topology-service" key={s.id}>{s.name}<Badge status={s.status}/></span>)}<Link className="a-more" to="/cockpit">Host controls →</Link></div>)}</div></div><p className="a-stamp">Service placement from the available monitoring snapshot. This map does not infer physical network links.</p><ErrorText error={snapshot.error}/></Panel>}
 <Panel title="Specialist tools" aside={<FileText size={18}/>}><div className="a-tool-grid">{tools.filter(t=>t.name!=='Streams').map(t=><a className="a-tool" href={LEGACY+t.path} target="_blank" rel="noreferrer" key={t.path}><span><strong>{t.name}</strong><small>{t.description}</small></span><ArrowUpRight size={17}/></a>)}</div></Panel></>;
}
