import { useState } from 'react';
import { Link,useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Plus,PanelsTopLeft,ArrowUpRight,Trash2,Settings2,Database,Bookmark } from 'lucide-react';
import { useCapabilities,useMode,usePreferences,useSavePreferences,LEGACY,tools,type Mode } from './data';
import { Heading,Panel,Empty,ErrorText,Dialog,Stamp } from './ui';
import { useBoards,useCreateBoard,useDeleteBoard } from '../lib/boards';
import { get } from '../lib/api';
const datasets=[{name:'Fleet vitals',route:'/api/vitals'},{name:'Containers',route:'/api/containers'},{name:'Activity',route:'/api/activity'},{name:'Scheduled work',route:'/api/timers'},{name:'Database status',route:'/api/hldb/status'},{name:'Database schema',route:'/api/hldb/schema'},{name:'Recent changes',route:'/api/hldb/changes'}];
export function Workspace({settings=false}:{settings?:boolean}){
 const [params,setParams]=useSearchParams();const tab=settings?'settings':(params.get('tab')||'boards');const prefs=usePreferences();const save=useSavePreferences();const caps=useCapabilities();const mode=useMode();const boards=useBoards();const create=useCreateBoard();const remove=useDeleteBoard();const [name,setName]=useState('');const [adding,setAdding]=useState(false);const [deleting,setDeleting]=useState<string|null>(null);const [dataset,setDataset]=useState(datasets[0].route);
 const data=useQuery({queryKey:['astra-explorer',dataset,caps.data?.mode],queryFn:()=>get<unknown>(dataset,15000),enabled:tab==='data'});
 return <><Heading eyebrow="WORKSPACE" title="Your workspace" description="Boards, saved filters, data exploration and preferences." actions={tab==='boards'?<button className="a-button" onClick={()=>setAdding(true)}><Plus size={17}/> New board</button>:undefined}/>{!settings&&<div className="a-tabs" aria-label="Workspace sections">{[['boards','Boards'],['views','Saved views'],['data','Data explorer'],['settings','Preferences']].map(([id,label])=><button key={id} className={tab===id?'active':''} aria-pressed={tab===id} onClick={()=>setParams({tab:id})}>{label}</button>)}</div>}<ErrorText error={save.error||prefs.error||boards.error||remove.error}/>
 {tab==='boards'&&<><div className="a-board-list">{boards.data?.boards.map(b=><div className="a-board-tile" key={b.slug}><Link to={`/workspace/boards/${b.slug}`}><PanelsTopLeft size={28}/><h2>{b.name}</h2><p>{b.widgets} widgets · {b.protected?'built-in board':'your board'}</p><span className="a-more">Open board <ArrowUpRight size={15}/></span></Link>{!b.protected&&<button className="a-icon a-board-delete" aria-label={`Delete board ${b.name}`} onClick={()=>setDeleting(b.slug)}><Trash2 size={16}/></button>}</div>)}</div><Panel title="Your existing tools"><div className="a-tool-grid">{tools.map(t=><a className="a-tool" href={LEGACY+t.path} target="_blank" rel="noreferrer" key={t.path}><span><strong>{t.name}</strong><small>{t.description}</small></span><ArrowUpRight size={16}/></a>)}</div></Panel></>}
 {tab==='views'&&<Panel title="Saved operations views" aside={<Bookmark size={18}/>}><p className="a-muted">Save a combination of host, severity, and search filters from Operations.</p>{prefs.data?.savedViews.map((v,i)=><div className="a-row" key={v.name+i}><Link to={v.path}>{v.name}</Link><button className="a-icon" aria-label={`Remove saved view ${v.name}`} disabled={save.isPending} onClick={()=>prefs.data&&save.mutate({...prefs.data,savedViews:prefs.data.savedViews.filter((_,j)=>i!==j)})}><Trash2 size={16}/></button></div>)}{!prefs.data?.savedViews.length&&<Empty>No saved views yet. <Link to="/operations">Explore findings</Link></Empty>}</Panel>}
 {tab==='data'&&<Panel title="Data explorer" aside={<Database size={18}/>}><p className="a-muted">Inspect existing read models. Arbitrary SQL execution is disabled in preview.</p><div className="a-toolbar"><label className="a-field">Dataset<select value={dataset} onChange={e=>setDataset(e.target.value)}>{datasets.map(d=><option key={d.route} value={d.route}>{d.name}</option>)}</select></label><button className="a-button" disabled={data.isFetching} onClick={()=>data.refetch()}>Refresh dataset</button></div><ErrorText error={data.error}/>{data.isFetching&&<p className="a-muted">Reading dataset…</p>}{data.data!==undefined&&<><Stamp value={new Date(data.dataUpdatedAt).toISOString()}/><pre className="a-json" tabIndex={0}>{JSON.stringify(data.data,null,2)}</pre></>}</Panel>}
 {tab==='settings'&&prefs.data&&<div className="a-detail-grid"><Panel title="Appearance" aside={<Settings2 size={18}/>}><label className="a-field">Theme<select value={prefs.data.theme} disabled={save.isPending} onChange={e=>prefs.data&&save.mutate({...prefs.data,theme:e.target.value as 'dark'|'light'})}><option value="dark">Gruvbox Dark</option><option value="light">Gruvbox Light</option></select></label><label className="a-field">Density<select value={prefs.data.density} disabled={save.isPending} onChange={e=>prefs.data&&save.mutate({...prefs.data,density:e.target.value as 'comfortable'|'compact'})}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label className="a-check"><input type="checkbox" checked={prefs.data.reducedMotion} disabled={save.isPending} onChange={e=>prefs.data&&save.mutate({...prefs.data,reducedMotion:e.target.checked})}/> Reduce motion (also respects system preference)</label><p className="a-stamp">Appearance and personalization are saved in this preview only.</p></Panel><Panel title="Preview data"><label className="a-field">Data mode<select aria-label="Preview data mode" value={caps.data?.mode||'demo'} disabled={mode.isPending} onChange={e=>mode.mutate(e.target.value as Mode)}><option value="demo">Demo — offline sample data</option><option value="live-readonly">Live — read-only monitoring</option></select></label><ErrorText error={mode.error}/><p className="a-muted">Demo mode never contacts your homelab. Live mode reads the existing Pi API while keeping operational controls disabled. A server restart defaults back to demo.</p><p className="a-muted">A VPN connection and access to the Pi are needed for live data. Connection errors remain visible.</p><a className="a-more" href="/astra-preview.html" target="_blank" rel="noreferrer">Open standalone design preview <ArrowUpRight size={15}/></a></Panel></div>}
 {adding&&<Dialog title="Create a board" onClose={()=>setAdding(false)}><form onSubmit={e=>{e.preventDefault();create.mutate(name,{onSuccess:()=>{setAdding(false);setName('')}})}}><label className="a-field">Board name<input required autoFocus maxLength={40} value={name} onChange={e=>setName(e.target.value)}/></label><button className="a-button primary" disabled={create.isPending}>Create board</button><ErrorText error={create.error}/></form></Dialog>}
 {deleting&&<Dialog title="Delete this board?" onClose={()=>setDeleting(null)}><p className="a-muted">This removes the local board layout. Your homelab services are unaffected.</p><button className="a-button" disabled={remove.isPending} onClick={()=>remove.mutate(deleting,{onSuccess:()=>setDeleting(null)})}>Delete board</button><ErrorText error={remove.error}/></Dialog>}</>;
}
